<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [10]:
import os
import pandas as pd
import numpy as np
import datetime as dt
from dateutil.relativedelta import relativedelta

In [11]:
def rec_disc_function(curr: float, exp: float, dmd=0):
    """
    Recommendation Objective function
    curr: Current Utilization Rate (0 < curr < 1)
    exp: Expected Utilization rate (0 < exp < 1)
    dmd: Expected Demand Change Rate (float)
    """
    # Hyper-parameters (need to tune)
    theta_1 = 1     # Ratio of Decreasing magnitude
    if curr < exp:  # Ratio of increasing magnitude
        theta_1 = 0.7
    theta_2 = 1     # Ratio of Demand magnitude

    # Suggestion curve bend
    # 1 < phi_low < phi_high < 2
    # phi_low = 1.7
    phi_high = 1.2

    y = 1 - theta_1 * (curr ** (phi_high ** (-1 * curr)) - exp * (1 - theta_2 * dmd))

    return y

In [27]:
def apply_disc_policy(disc_list: list):
    temp = np.where(np.array(disc_list) > 80, 80, disc_list)
    vfunc = np.vectorize(conv_to_five_times)
    result = vfunc(temp)
    
    return result

In [29]:
def conv_to_five_times(discount):
    if discount % 5 >= 2.5:
        return (discount // 5 + 1) * 5
    else:
        return (discount // 5) * 5

In [48]:
applied_disc_1 = [60, 60, 60, 75, 75 ,75 ,75 ,60, 60, 60, 75, 75]

In [58]:
applied_disc = [val - 15 for val in applied_disc_1]

In [72]:
applied_disc

[45, 45, 45, 60, 60, 60, 60, 45, 45, 45, 60, 60]

In [59]:
av_ad = [1.232, 1.132, 1.008, 0.963, 0.908, 0.952, 0.979, 0.957, 0.902, 0.806, 0.896, 1.002]
av_new = [1.169, 1.101, 1.043, 1.105, 1.03, 1.028, 0.911, 0.755, 0.632, 0.678, 0.74, 0.863]
k3 = [1.14, 1.044, 0.918, 0.931, 0.918, 0.916, 0.818, 0.774, 0.779, 0.702, 0.853, 0.986]
soul = [1.142, 1.005, 1.01, 0.915, 1.011, 0.964, 0.837, 0.858, 0.853, 0.824, 1.028, 1.11]
vlst = [1.059, 1.031, 0.844, 0.945,  1.013, 0.992, 1.055, 0.979, 0.814, 0.782, 0.83, 1.017]

In [60]:
av_ad_af = [disc * rate for disc, rate in zip(applied_disc, av_ad)]
av_new_af = [disc * rate for disc, rate in zip(applied_disc, av_new)]
k3_af = [disc * rate for disc, rate in zip(applied_disc, k3)]
soul_af = [disc * rate for disc, rate in zip(applied_disc, soul)]
vlst_af = [disc * rate for disc, rate in zip(applied_disc, vlst)]

In [61]:
av_ad_af_new = apply_disc_policy(disc_list = av_ad_af)
av_new_af_new = apply_disc_policy(disc_list = av_new_af)
k3_af_new = apply_disc_policy(disc_list = k3_af)
soul_af_new = apply_disc_policy(disc_list = soul_af)
vlst_af_new = apply_disc_policy(disc_list = vlst_af)

In [67]:
av_ad_af_new.astype(int)

array([55, 50, 45, 60, 55, 55, 60, 45, 40, 35, 55, 60])

In [68]:
av_new_af_new.astype(int)

array([55, 50, 45, 65, 60, 60, 55, 35, 30, 30, 45, 50])

In [69]:
k3_af_new.astype(int)

array([50, 45, 40, 55, 55, 55, 50, 35, 35, 30, 50, 60])

In [70]:
vlst_af_new.astype(int)

array([50, 45, 40, 55, 60, 60, 65, 45, 35, 35, 50, 60])

In [71]:
soul_af_new.astype(int)

array([50, 45, 45, 55, 60, 60, 50, 40, 40, 35, 60, 65])